import "server-only";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

import type { AssessmentInput, AssessmentResult } from "@/lib/assessment/scoring";
import { services } from "@/lib/data/services";
import { aiWorkforce } from "@/lib/data/ai-workforce";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#0F172A",
  },
  eyebrow: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 2,
    color: "#2563EB",
    marginBottom: 8,
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 11,
    color: "#475569",
    marginBottom: 24,
  },
  scoreRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 24,
  },
  scoreBox: {
    flex: 1,
    padding: 12,
    borderRadius: 6,
    backgroundColor: "#F1F5F9",
  },
  scoreValue: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 2,
  },
  scoreLabel: {
    fontSize: 9,
    color: "#475569",
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 8,
    marginTop: 16,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "#2563EB",
  },
  bullet: {
    flexDirection: "row",
    marginBottom: 4,
  },
  bulletDot: {
    width: 10,
  },
  footer: {
    marginTop: 32,
    fontSize: 9,
    color: "#94A3B8",
  },
});

export function AssessmentPdfReport({
  input,
  result,
}: {
  input: AssessmentInput;
  result: AssessmentResult;
}) {
  const recommendedServices = result.recommendedServices
    .map((slug) => services.find((service) => service.slug === slug)?.title)
    .filter((title): title is string => Boolean(title));

  const recommendedWorkforce = result.recommendedWorkforce
    .map((slug) => aiWorkforce.find((employee) => employee.slug === slug)?.title)
    .filter((title): title is string => Boolean(title));

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.eyebrow}>AIQEN — AI BUSINESS ASSESSMENT</Text>
        <Text style={styles.title}>{input.company}</Text>
        <Text style={styles.subtitle}>Prepared for {input.name} · {new Date().toLocaleDateString()}</Text>

        <View style={styles.scoreRow}>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreValue}>{result.automationReadiness}</Text>
            <Text style={styles.scoreLabel}>Automation Readiness</Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreValue}>{result.aiReadiness}</Text>
            <Text style={styles.scoreLabel}>AI Readiness</Text>
          </View>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreValue}>{result.opportunityScore}</Text>
            <Text style={styles.scoreLabel}>Opportunity Score</Text>
          </View>
        </View>

        <Text style={styles.sectionTitle}>Estimated Impact</Text>
        <Text>~{result.estimatedHoursSavedPerWeek} hours saved per week</Text>
        <Text>~${result.estimatedMonthlySavings.toLocaleString()} estimated monthly savings</Text>

        <Text style={styles.sectionTitle}>Recommended Services</Text>
        {recommendedServices.length === 0 ? (
          <Text>No specific services flagged — general AI consulting is a good starting point.</Text>
        ) : (
          recommendedServices.map((title) => (
            <View key={title} style={styles.bullet}>
              <Text style={styles.bulletDot}>•</Text>
              <Text>{title}</Text>
            </View>
          ))
        )}

        <Text style={styles.sectionTitle}>Recommended AI Workforce</Text>
        {recommendedWorkforce.length === 0 ? (
          <Text>No specific roles flagged yet — a discovery call will help pinpoint the best fit.</Text>
        ) : (
          recommendedWorkforce.map((title) => (
            <View key={title} style={styles.bullet}>
              <Text style={styles.bulletDot}>•</Text>
              <Text>{title}</Text>
            </View>
          ))
        )}

        <Text style={styles.sectionTitle}>Recommended Plan</Text>
        <Text>{result.recommendedPlan}</Text>

        <Text style={styles.footer}>
          Generated by AIQEN&apos;s AI Business Assessment. This is an automated estimate based on the
          information you provided — book a call with our team for a tailored recommendation.
        </Text>
      </Page>
    </Document>
  );
}
